### ISSUE TITLE
Transmission returning value too large for Int32

### ISSUE THREAD

**Issue by JustSomeGuyNZ** [trossr32/ps-transmission#13]
Get-TransmissionTorrents
Get-TransmissionTorrents: Failed to retrieve torrents with error: One or more errors occurred. (JSON integer 20263907328 is too large or small for an Int32. Path 'torrents[139].corruptEver', line 1, position 1664164.)

Get-TransmissionTorrents -TorrentIds 444
Get-TransmissionTorrents: Failed to retrieve torrents with error: One or more errors occurred. (JSON integer 20251148288 is too large or small for an Int32. Path 'torrents[0].corruptEver', line 1, position 123.)

**Comment by trossr32** [comment]
Fixed in v1.0.9
